export const CONFIG = {
    REACT_APP_GITHUB_OAUTH_CLIENT_ID:process.env.REACT_APP_GITHUB_OAUTH_CLIENT_ID,
    REACT_APP_SERVER_URL:process.env.REACT_APP_SERVER_URL,
    REACT_APP_CLIENT_CALLBACK:process.env.REACT_APP_CLIENT_CALLBACK,
    REACT_APP_GITHUB_LOGIN_URL: process.env.REACT_APP_GITHUB_LOGIN_URL
}
console.log(CONFIG);